# Generated by Django 5.2.3 on 2025-06-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='bus',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
